version: '2'
services:
  oracle-xe:
    image: oracle/database:21.3.0-xe
    restart: always
#   network_mode: host # if host network
    volumes:
      - ${ORACLE_MOUNT}:/opt/oracle/oradata
    environment:
      - ORACLE_SID=XE # Express Edition Docker-image hard cording
      - ORACLE_PDB=XEPDB1 # Express Edition Docker-image hard cording
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
    ports:
      - "1521:1521"
      - "5500:5500" # for Enterprise Manager
